# conduwuit
version: '2.4' # uses '2.4' for cpuset

services:
    homeserver:
        ### If you already built the conduwuit image with 'docker build' or want to use a registry image,
        ### then you are ready to go.
        image: girlbossceo/conduwuit:latest
        restart: unless-stopped
        ports:
            - 8448:6167
        volumes:
            - db:/var/lib/conduwuit
            #- ./conduwuit.toml:/etc/conduwuit.toml
        environment:
            CONDUWUIT_SERVER_NAME: your.server.name # EDIT THIS
            CONDUWUIT_DATABASE_PATH: /var/lib/conduwuit
            CONDUWUIT_DATABASE_BACKEND: rocksdb
            CONDUWUIT_PORT: 6167
            CONDUWUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
            CONDUWUIT_ALLOW_REGISTRATION: 'true'
            CONDUWUIT_ALLOW_FEDERATION: 'true'
            CONDUWUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
            CONDUWUIT_TRUSTED_SERVERS: '["matrix.org"]'
            #CONDUWUIT_LOG: warn,state_res=warn
            CONDUWUIT_ADDRESS: 0.0.0.0
            #CONDUWUIT_CONFIG: './conduwuit.toml' # Uncomment if you mapped config toml above
        #cpuset: "0-4" # Uncomment to limit to specific CPU cores
    #
    ### Uncomment if you want to use your own Element-Web App.
    ### Note: You need to provide a config.json for Element and you also need a second
    ###       Domain or Subdomain for the communication between Element and conduwuit
    ### Config-Docs: https://github.com/vector-im/element-web/blob/develop/docs/config.md
    # element-web:
    #     image: vectorim/element-web:latest
    #     restart: unless-stopped
    #     ports:
    #         - 8009:80
    #     volumes:
    #         - ./element_config.json:/app/config.json
    #     depends_on:
    #         - homeserver

volumes:
    db:
